name: Deploy Bot

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd /home/admin/bots/EventRelayer/lore-event-relay
          git pull origin main

      - name: Restart Bot
        run: |
          sudo systemctl restart EventRelayer

